### ISSUE TITLE
Please clarify how to use with rbenv / rvm

### ISSUE THREAD

**Issue by sporto** [nicolai86/ansible-rails-deployment#10]
In the readme you have:

```
If you are using rbenv to manage your ruby version make sure to properly set the environment using something like this:

environment:
  PATH: '~/.rbenv/shims:~/.rbenv/bin:"$PATH"'
```

I am not clear at all, where is this supposed to go, something like this?

```
    - role: nicolai86.rails-deployment
      ...
      environment:
         PATH: '~/.rbenv/shims:~/.rbenv/bin:"$PATH"'
```

I'm using RVM and just getting this error:

```
failed: [xxx.xxx.xxx.xxx] => {"changed": false, "cmd": "bundle install --path=/var/www/appname/shared/vendor/bundle --gemfile=./Gemfile --deployment --binstubs=./bin", "failed": true, "rc": 2}
msg: [Errno 2] No such file or directory
```

Thanks
