### ISSUE TITLE
"Copy asset files when not changed" creates recursive directory structure

### ISSUE THREAD

**Issue by kjleitz** [nicolai86/ansible-rails-deployment#16]
https://github.com/nicolai86/ansible-rails-deployment/blob/79b8c10658a05d23bccf35698830374f1f592900/tasks/main.yml#L55

```yaml
- name: copy asset files when not changed
  shell: "cp -R {{ current_path }}/public/assets {{ build_path }}/public/assets"
  when: compile_assets and assets is defined and not assets.changed
```

For example, given a `current_path` of `some_current_dir/` and a `build_path` of `some_build_dir/`, this seems to create a `some_build_dir/public/assets/assets` (notice that it's _nested)_ linking to `some_current_dir/public/assets`.

I may be misunderstanding, but isn't this action supposed to link

```
some_build_dir/public/assets
```

to

```
some_current_dir/public/assets
```

...?

_Not_ to link

```
some_build_dir/public/assets/assets
```

to

```
some_current_dir/public/assets
```

...?

Thank you for this repo, by the way, it's a huge help!
