### ISSUE TITLE
Playbook dependencies cause duplicate executions per example

### ISSUE THREAD

**Issue by nbibler** [nicolai86/ansible-rails-deployment#6]
Using your [latest Gist example](https://gist.github.com/nicolai86/8950790) on how to use rails-deployment as of v0.6.0, the current ansible-rails-deployment causes playbooks to repeat execution:

```
$ ansible --version
ansible 1.6.1
$ ansible-galaxy list
 nicolai86.deployment-facts, v0.1.2
 nicolai86.deployment-rollback, v0.1.1
 nicolai86.finalize-release, v0.1
 nicolai86.prepare-release, v0.2.0
 nicolai86.rails, v0.6.3
 nicolai86.rails-deployment, v0.6.7
```

``` yaml

---
- hosts: webservers
  user: deploy
  gather_facts: False

  vars:
    user: deploy
    deploy_to: "/srv/example-dest"


  roles:
    - role: nicolai86.prepare-release
      tags: app

      repo: git@server.com:example.git
      branch: master

      symlinks:
        - { src: "{{ shared_path }}/vendor/bundle", dest: "{{ build_path }}/vendor/bundle" }
        - { src: "{{ shared_path }}/.env", dest: "{{ build_path }}/.env" }

      directories:
        - "{{ shared_path }}/config"
        - "{{ shared_path }}/log"
        - "{{ shared_path }}/public"


    - role: nicolai86.rails-deployment
      tags: app

      migrate: yes
      compile_assets: yes
      force_migrate: no
      force_asset_compilation: no


    - role: nicolai86.finalize-release
      tags: app


    - role: nicolai86.deployment-rollback
      tags: rollback
```

```
PLAY [webservers] *************************************************************

TASK: [nicolai86.prepare-release | deployment_facts] **************************
ok: [server-1]

TASK: [nicolai86.prepare-release | create shared directories] *****************
ok: [server-1] => (item=/srv/example-dest)
ok: [server-1] => (item=/srv/example-dest/releases)
ok: [server-1] => (item=/srv/example-dest/shared)
ok: [server-1] => (item=/srv/example-dest/shared/vendor)
ok: [server-1] => (item=/srv/example-dest/shared/vendor/bundle)
ok: [server-1] => (item=/srv/example-dest/shared/config)
ok: [server-1] => (item=/srv/example-dest/shared/log)
ok: [server-1] => (item=/srv/example-dest/shared/public)

TASK: [nicolai86.prepare-release | create configuration files from templates] ***
skipping: [server-1]

TASK: [nicolai86.prepare-release | create or update the bare Git repository] ***
ok: [server-1]

TASK: [nicolai86.prepare-release | shell chdir="{{deploy_to}}/scm" git archive {{branch}} | tar -x -C {{build_path}}] ***
changed: [server-1]

TASK: [nicolai86.prepare-release | correct build directory permissions] *******
changed: [server-1]

TASK: [nicolai86.prepare-release | symlink shared files to build directory] ***
changed: [server-1] => (item={'dest': u'/tmp/tmpSR1gMG/vendor/bundle', 'src': u'/srv/example-dest/shared/vendor/bundle'})
changed: [server-1] => (item={'dest': u'/tmp/tmpSR1gMG/.env', 'src': u'/srv/example-dest/shared/.env'})

TASK: [nicolai86.prepare-release | deployment_facts] **************************
ok: [server-1]

TASK: [nicolai86.prepare-release | create shared directories] *****************
ok: [server-1] => (item=/srv/example-dest)
ok: [server-1] => (item=/srv/example-dest/releases)
ok: [server-1] => (item=/srv/example-dest/shared)
ok: [server-1] => (item=/srv/example-dest/shared/vendor)
ok: [server-1] => (item=/srv/example-dest/shared/vendor/bundle)

TASK: [nicolai86.prepare-release | create configuration files from templates] ***
skipping: [server-1]

TASK: [nicolai86.prepare-release | create or update the bare Git repository] ***
fatal: [server-1] => One or more undefined variables: 'repo' is undefined

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/...retry

server-1               : ok=9    changed=3    unreachable=1    failed=0
```

In this case, you can see that `deployment_facts` runs twice, and `prepare-release` is starting from the beginning.  And, in this case, because my `repo` variable isn't defined at the top of the Playbook, it actually fails because the dependency execution is not configured with the proper variables.
